import numpy as np
from rocketpy.rocket.aero_surface import TrapezoidalFins, EllipticalFins
from controls.controls import Controls

class Fins(TrapezoidalFins):
    def __init__(
        self,
        n,
        root_chord,
        tip_chord,
        span,
        rocket_radius,
        cant_angle=0,
        sweep_length=None,
        sweep_angle=None,
        airfoil=None,
        name="Fins",
    ):
        super().__init__(
            n,
            root_chord,
            tip_chord,
            span,
            rocket_radius,
            cant_angle,
            sweep_length,
            sweep_angle,
            airfoil,
            name,
        )

        self.aileronAngles = np.array([0.0])
        self.controller : Controls = None
        
    def set_controller(self, controller: Controls):
        """Setter for the controller object. Used to get user-defined control input physics (e.g. aileron aerodynamics).

        Args:
            controller (Controls): The controller object to be used for fin control.
        """
        self.controller = controller

    def compute_forces_and_moments(
        self,
        stream_velocity,
        stream_speed,
        stream_mach,
        rho,
        cp,
        omega,
        *args,
    ): 
        R1, R2, R3, M1, M2, M3 = super().compute_forces_and_moments(
            stream_velocity,
            stream_speed,
            stream_mach,
            rho,
            cp,
            omega,
            *args,
        )

        Mx, My, Mz = self.input_func(stream_velocity)
        M3 = M3 + Mz
        M2 = M2 + My
        M1 = M1 + Mx
        return R1, R2, R3, M1, M2, M3
    
    
    def input_func(self, stream_velocity):
        """Compute the moment generated by the ailerons based on vertical velocity.

        Args:
            stream_velocity (list or np.ndarray): Stream velocity vector in the body frame.

        Returns:
            float: Moment generated by the ailerons.
        """
        v1, v2, v3 = stream_velocity[0], stream_velocity[1], stream_velocity[2]
        delta1 = self.aileronAngles
        state = np.array([0.0, 0.0, 0.0, v1, v2, v3, 0.0, 0.0, 0.0, 0.0])
        input = np.array([delta1[0]])
        Mx, My, Mz = self.controller.M_controls_func(state, input)
        
        return [Mx, My, Mz]