# rl_rollrate_train.py
# Train an RL policy to minimize |w3| by actuating aileron deflection.
# Uses your existing dynamics exactly as AX + BU - L(CX - Y).
import os
import numpy as np
from pathlib import Path

# === Gym/Gymnasium spaces; SB3 PPO ===
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold
from stable_baselines3.common.monitor import Monitor

# === Import your dynamics (DO NOT MODIFY) ===
from control_algorithm import Controls
# We don't need silsim/rocketpy for training—this is a fast, model-based rollouts loop.

DEG = np.pi / 180.0

class RollRateEnv(gym.Env):
    """
    Observation: xhat (10,) = [w1,w2,w3, v1,v2,v3, qw,qx,qy,qz]
    Action:      aileron deflection delta1 in radians, clipped to [-8°, +8°]
    Reward:      -( |w3| ) - λ_u * u^2 - λ_du * (Δu)^2
    Dynamics step: x_{t+1} = x + dt*(A x + B u + a_T + a_g - L(Cx - y))
      with y generated by your deriveSensorModels() using current attitude/gyro.
    Episode ends at t >= t_estimated_apogee, or (t>burnout and v3<=0).
    """
    metadata = {"render.modes": ["human"]}

    def __init__(
        self,
        dt=1/40.0,
        seed=42,
        w3_init_range=(0.0, 0.0),     # randomize initial roll rate [rad/s]
        K_sched=None,
        L_gains=None,
    ):
        super().__init__()
        self.rng = np.random.default_rng(seed)
        self.dt = float(dt)

        # --- Build your Controls object without changing its code ---
        self.ctrl = Controls(dt=self.dt,
                             x0=np.array([0,0,0, 0,0,0, 1,0,0,0], dtype=float),
                             u0=np.array([0.0], dtype=float),
                             t_launch_rail_clearance=0.308)
        self.ctrl.setup_EOM()

        # Gain scheduling K is not used to compute action (RL does),
        # but we keep it defined so A,B can depend on same context if needed.
        if K_sched is None:
            self.ctrl.set_K_params(K_pre_max=0.5, K_pre_min=0.5,
                                   K_post_max=0.5, K_post_min=0.5,
                                   pre_width=3.0, post_width=8.0,
                                   pre_v3_mid=100.0, post_v3_mid=90.0)
        else:
            self.ctrl.set_K_params(**K_sched)

        # Observer gain L (used inside AX+BU-L(CX-Y))
        if L_gains is None:
            lw = 5e-3
            lq = 5e-3
            self.ctrl.buildL(lw=lw, lqw=lq, lqx=lq, lqy=lq, lqz=lq)
        else:
            self.ctrl.buildL(**L_gains)

        # Action: aileron (radians)
        self.u_min = -8.0 * DEG
        self.u_max = +8.0 * DEG
        self.action_space = spaces.Box(low=np.array([self.u_min], dtype=np.float32),
                                       high=np.array([self.u_max], dtype=np.float32),
                                       dtype=np.float32)

        # Observation: xhat (10,)
        high = np.array([np.inf]*10, dtype=np.float32)
        self.observation_space = spaces.Box(low=-high, high=high, dtype=np.float32)

        # Reward weights
        self.lam_u  = 1e-3   # action penalty
        self.lam_du = 5e-3   # action rate penalty

        self.w3_init_range = w3_init_range
        self.reset()

    # --- Utility: make a measurement y from current xhat via your sensor model ---
    def _measurement_from_state(self, t, x):
        # x -> (theta,phi,psi) from quaternion
        qw, qx, qy, qz = x[6:10]
        theta, phi, psi = self.ctrl.quat_to_euler_xyz([qw, qx, qy, qz])
        # feed current true angular rates (we use xhat as truth in this model-based loop)
        y = self.ctrl.deriveSensorModels(t, x[0], x[1], x[2], theta, phi, psi)  # [gw1,gw2,gw3,qw,qx,qy,qz]
        return y

    def _done(self, t, x):
        # "apogee" proxy: if past burnout and vertical body velocity v3 non-positive,
        # or we simply ran to estimated apogee time.
        v3 = float(x[5])
        past_burnout = (t > self.ctrl.t_motor_burnout)
        if (past_burnout and v3 <= 0.0):
            return True
        if t >= self.ctrl.t_estimated_apogee:
            return True
        return False

    def reset(self, *, seed=None, options=None):
        if seed is not None:
            self.rng = np.random.default_rng(seed)
        self.t = 0.0
        self.prev_u = 0.0

        # Start near liftoff; small random initial roll & small forward velocity
        w3_0 = self.rng.uniform(self.w3_init_range[0], self.w3_init_range[1]) * (1 if self.rng.random()<0.5 else -1)
        self.x = np.array([0.0, 0.0, w3_0,  # w1, w2, w3
                           0.0, 0.0, 0.5,   # v1, v2, v3
                           1.0, 0.0, 0.0, 0.0], dtype=float)  # unit quaternion

        obs = self.x.astype(np.float32)
        info = {}
        return obs, info

    def step(self, action):
        # Clip and cast action
        u = float(np.clip(action[0], self.u_min, self.u_max))
        # Compute A,B,C at current (t, x, u_prev) — this is how your code does it
        u_prev = np.array([self.prev_u], dtype=float)
        self.ctrl.computeAB(t=self.t, xhat=self.x, u=u_prev)
        self.ctrl.computeC(xhat=self.x, u=u_prev)
        A = np.array(self.ctrl.A, dtype=float)
        B = np.array(self.ctrl.B, dtype=float)
        C = np.array(self.ctrl.C, dtype=float)

        # Input used by observer update is *current* u
        u_vec = np.array([u], dtype=float)

        # Build y from current state via your sensor model (adds noise & biases)
        y = self._measurement_from_state(self.t, self.x)

        # Thrust + gravity accelerations from your helpers
        aT = self.ctrl.get_thrust_accel(t=self.t)         # (10,)
        aG = self.ctrl.get_gravity_accel(xhat=self.x)     # (10,)

        # Observer/Luenberger step with your L:
        L = np.array(self.ctrl.L, dtype=float)
        xdot = A @ self.x + B @ u_vec + aT + aG - L @ (C @ self.x - y)
        x_next = self.x + self.dt * xdot

        # Normalize quaternion to avoid drift
        qn = np.linalg.norm(x_next[6:10])
        if qn > 1e-12:
            x_next[6:10] = x_next[6:10] / qn
        else:
            x_next[6:10] = np.array([1.0, 0.0, 0.0, 0.0])

        # Reward: penalize |w3|, action use, and action rate
        w3 = float(x_next[2])
        du = u - self.prev_u
        reward = -(abs(w3) + self.lam_u * (u**2) + self.lam_du * (du**2))

        # Advance
        self.x = x_next
        self.t += self.dt
        self.prev_u = u

        terminated = self._done(self.t, self.x)
        truncated = False
        obs = self.x.astype(np.float32)
        info = {"t": self.t, "w3": w3, "u": u, "v3": float(self.x[5])}
        return obs, reward, terminated, truncated, info

    def render(self):
        print(f"t={self.t:.2f}s  w3={self.x[2]: .3f} rad/s  u={self.prev_u/DEG: .2f} deg  v3={self.x[5]: .2f} m/s")

def main():
    # --- Build env ---
    env = RollRateEnv(dt=1/40.0)
    env = Monitor(env)  # SB3 monitor wrapper for logging

    # --- PPO config (light but effective for this task) ---
    policy_kwargs = dict(net_arch=[128, 128])
    model = PPO(
        policy="MlpPolicy",
        env=env,
        learning_rate=3e-4,
        n_steps=1024,
        batch_size=256,
        n_epochs=10,
        gamma=0.995,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.0,
        vf_coef=0.5,
        policy_kwargs=policy_kwargs,
        verbose=1,
        tensorboard_log="./tb_rollrate/",
    )

    # --- Early stop when we consistently drive |w3| low ---
    # Because reward ~ -|w3| with small penalties, a threshold like -0.02
    # means average |w3| is about 0.02 rad/s for the episode.
    callback = EvalCallback(
        env,
        best_model_save_path="./rl_rollrate_best/",
        log_path="./rl_rollrate_logs/",
        eval_freq=5000,
        deterministic=True,
        render=False,
        callback_after_eval=StopTrainingOnRewardThreshold(reward_threshold=-0.02, verbose=1),
        n_eval_episodes=5,
    )

    timesteps = 300_000
    model.learn(total_timesteps=timesteps, callback=callback, progress_bar=True)
    model.save("ppo_rollrate_aileron.zip")
    print("Training complete. Saved to ppo_rollrate_aileron.zip")

    # Quick eval rollout:
    obs, _ = env.reset(seed=123)
    ret = 0.0
    for _ in range(1500):
        action, _ = model.predict(obs, deterministic=True)
        obs, r, term, trunc, info = env.step(action)
        ret += r
        if term or trunc:
            break
    print(f"Eval return: {ret:.3f}; final |w3|={abs(info['w3']):.4f} rad/s")

if __name__ == "__main__":
    main()
